version: '3'
services:
  lb:
    image: dockercloud/haproxy
    links:
      - api-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    restart: on-failure

  api-gateway:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/api-gateway:dev
    restart: on-failure
    environment:
      - VIRTUAL_HOST=api-gateway.app.com
    ports:
      - 3000:3000
    volumes:
      - ./api-gateway:/app/src

  ms-emails:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/ms-emails:dev
    restart: on-failure
    volumes:
      - './ms-emails:/app/src'

  ms-analytics:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: microservices-workshop/ms-analytics:dev
    restart: on-failure
    volumes:
      - ./ms-analytics:/app/src

